FROM debian:stable-slim

RUN  apt-get update \
  && apt-get install -y wget \
  && cd /tmp/ \
  && wget -q https://github.com/OmniDB/OmniDB/releases/download/2.17.0/omnidb-server_2.17.0-debian-amd64.deb \
  && dpkg -i omnidb-app_2.17.0-debian-amd64.deb \
  && mkdir -p /data \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /tmp/*

EXPOSE 8000
EXPOSE 25482

VOLUME ["/data"]
CMD ["omnidb-server", "-H", "0.0.0.0"]
