  
# Use phusion/baseimage as base image.
FROM phusion/baseimage:bionic-1.0.0

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN mkdir -p /etc/my_init.d

COPY scripts/* /etc/my_init.d/

ENV LISTENING_PORT="8080" \
LISTENING_ADDRESS="0.0.0.0" \
IS_SSL="" \
SSL_CERTIFICATE_FILE="" \
SSL_KEY_FILE="" \
SESSION_COOKIE_SECURE="" \
CSRF_COOKIE_SECURE=""

EXPOSE 8080

VOLUME ["/root/.omnidb/omnidb-server"]
